---
title: "flexdashboard_plot"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
data("ny_noaa")

## clean the dataset
ny_noaa = ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(col = date, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(tmax = as.numeric(tmax),
         tmin = as.numeric(tmin)) %>% 
  mutate(
    tmax = tmax/10,
    tmin = tmin/10,
    prcp = prcp/10
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, warning=FALSE}
ny_noaa %>% 
  filter(month == "01" & year %in% 2000:2007) %>% 
  group_by(year, id) %>%
  summarize(tmax_mean = mean(tmax, na.rm = T)) %>%
  plot_ly(x = ~factor(year), y = ~tmax_mean, type = "box", 
          color = ~factor(year)) %>% 
  layout(title = "Average tmax in January for each year",
         xaxis = list(title = "Year"),
         yaxis = list(title = "Average tmax"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, warning=FALSE}
ny_noaa %>% 
  filter(month == "01" & year == 2007) %>%
  mutate(text_label = str_c("ID: ", id, '\nDay: ', day)) %>%  
  plot_ly(x = ~tmin, y = ~tmax, type = "scatter", mode = "markers",
          text = ~text_label) %>% 
  layout(title = "Tmax and tmin in January, 2007")
```

### Chart C

```{r}
ny_noaa %>% 
  filter(month == "01" & year %in% 2000:2007) %>%
  group_by(year, month) %>% 
  summarize(snow_mean = mean(snow, na.rm = T)) %>% 
  plot_ly(x = ~factor(year), y = ~snow_mean, type = "bar", color = ~factor(year)) %>% 
  layout(title = "Average snowfall in January for each year",
         xaxis = list(title = "Year"))
```

